name: "Docker"

on:
  push:

jobs:
  build-docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: "bash -l -e -o pipefail {0}"

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Docker build"
        run: |
          cd docker
          docker build --rm \
            --build-arg HTSLIB_BRANCH=1.17 \
            -t gpig .
          docker run gpig
